### ISSUE TITLE
Add the ability to create a "Browser" / "Website" / HTML tab

### ISSUE THREAD

**Issue by jochenschmich** [OpenKneeboard/OpenKneeboard#233]
I would love to view my own Website https://efb.1stgw.com/ for Falcon BMS.
Would it be possible to integrate a Browser View into the App (so you could set an URL instead of a PDF / Image file)?

Cheers,
J

**Comment by fredemmott** [comment]
The next version includes support for window capture with tablet input forwarding, including with google chrome, and (mostly) edge

Given that, it’s fairly unlikely I’ll do something specialized, but not ruling it out for now

**Comment by jochenschmich** [comment]
Hi @fredemmott. Thanks for responding. Is there already a way to try the window capturing feature, or a bit of documentation?

**Comment by fredemmott** [comment]
https://github.com/OpenKneeboard/OpenKneeboard/releases/tag/v1.3.0 includes that feature

**Comment by fredemmott** [comment]
Added 'HTML' to the title to make this easier for me to search for

**Comment by fredemmott** [comment]
Two main potential approaches:

- [Chromium Embedded Framework](https://github.com/chromiumembedded)
- [WebView2](https://www.nuget.org/packages/Microsoft.Web.WebView2) - this is using Edge's engine, which is also Chromium nowadays.

While WinUI3's `Microsoft.UI.Xaml.WebView2` isn't suitable here (as we need to either render to a directx texture, or to a PDF, but that only supports direct usage in a window), C++/WinRT does add `winrt/Microsoft.Web.WebView2.Core.h`, including all of `CoreWebView2`. This probably makes it easier to fit into OpenKneeboard than CEF.

In particular, that supports [CoreWebView2Environment.CreateCoreWebView2ControllerAsync](https://learn.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2environment.createcorewebview2controllerasync?view=webview2-dotnet-1.0.1587.40#microsoft-web-webview2-core-corewebview2environment-createcorewebview2controllerasync(system-intptr)) , which in turn supports HWND_MESSAGE for a headless mode.

There's then two options:

- print-to-pdf, keep existing page-based model; probably good for falcon BMS, and probably comes first
- full-featured web browser. Would need OpenKneeboard to implement another toolbar (back/forward/home), scroll bar, etc - **but also requires using CEF instead of WebView2** - in particular, WebView2 does not appear to be capable of rendering to a directx texture. Copying every frame for the browser from GPU to CPU and back to the GPU again isn't going to be usable for high resolutions or e.g. videos

**Comment by RangeyRover** [comment]
just wanted to comment that this feature would be really useful for SimHub in racing sims, as Simhub dashboards can be rendered in any browser window. It's also the way the in game HUD is generated in RaceRoom using CEF, which appears natively in VR. The ability to have a transparent background in the web browser would be a key feature.

**Comment by fredemmott** [comment]
It looks like WebView2 may be possible via https://learn.microsoft.com/en-us/windows/uwp/composition/composition-native-interop , though it's unclear which parts of that require pre-release versions of windows.

**Comment by fredemmott** [comment]
For racing it's particularly important to be able to specify sound or aspect ratio, e.g. for simhub dashboards.

**Comment by fredemmott** [comment]
Not going to do this until/unless Microsoft address limitations of their engine:
- Embedded Chromium would need updating extremely frequently and rapidly to keep up with security updates. This is enough to rule it out for me just for the maintenance burden, but also:
- Embedded Chromium either needs patching, or will greatly increase CPU and GPU usage and be unsuitable for videos/animations: the only supported way to use it is via a main RAM bitmap, not via GPU
- Microsoft's WebView2 only supports directly rendering to a Window; there is a 'preview' API copying to RAM that might be a workaround, but it would have the same performance problems as Embedded Chromium. Hopefully this will change in the future.

**Comment by fredemmott** [comment]
So, working around those limitations by:
- creating an invisible window
- ... running window capture on that invisible window

![image](https://github.com/OpenKneeboard/OpenKneeboard/assets/360927/dcca2754-3e5f-40a7-a548-e9ac615c18a0)

Not yet usable.

**Comment by fredemmott** [comment]
CEF now has accelerated off-screen rendering support without a third-party patch (big thanks to @reitolab <3 ): https://github.com/chromiumembedded/cef/commit/260dd0ca24f9a8952f871dece2fcc10fe85d81fe

WebView2 still has the advantage of not needing to manage security updates.
