### ISSUE TITLE
Crash when switching tabs (especially quickly)

### ISSUE THREAD

**Issue by tanrr** [OpenKneeboard/OpenKneeboard#244]
If I have any DCS specific pages (except for theater) when I try to change to those pages in game (regardless of DCS plane, theater, etc.) I will either immediately or shortly thereafter have OpenKneeboard crash.

Most recent version 1.3.0, but have had this issue with all versions.  
Windows 11 22H2, OS build 22621.963, but had same issue with Windows 10.
Had previously updated Visual Studio redistributables to try to work around this, but problem still occurs.
(Have not tried updating them again - will do that next.)

I set it for full dump information this time.  With this last test I was able to briefly go between DCS Briefing, Mission, and Theater pages before it crashed.

Dumpfile is too large to upload here.  
Dropbox link for dump is https://www.dropbox.com/sh/hl5y4evnjidzxni/AAB9fK5uTa8QLWR4v_-GwrUia?dl=0 

Let me know if you want me to try anything specific for this.

**Comment by fredemmott** [comment]
Unfortunately, this will sometimes happen when changing tabs quickly, and needs to be fixed by microsoft :(

https://github.com/microsoft/microsoft-ui-xaml/issues/7254

**Comment by fredemmott** [comment]
Also, thank you so much for that dump - the dump made it super clear that it's that issue.

**Comment by fredemmott** [comment]
To reproduce reliably on v1.4-beta1 (which adds a 'repeat' parameter to the remote controls):

```
.\OpenKneeboard-RemoteControl-NEXT_TAB.exe 100
```

Also, I seem to have a workaround; there are two main ways to interact with the mouse when using directx in this kind of app:

- low latency, in another thread: recommended by Microsoft, crashes, can only be fixed by microsoft
- high latency, standard app mouse events: doesn't crash

The 'high latency' approach was unusably bad the last time I tried it, but seems good (unnoticable latency) now. Will try it in the next beta.
