### ISSUE TITLE
1.4-beta 3 small performance hits every second.

### ISSUE THREAD

**Issue by matthlsile** [OpenKneeboard/OpenKneeboard#280]
Hi,

in DCS with Openkneeboard 1.4 beta 3 running i see small performance hits **exactly every second**. See screenshots below. 
It doesn't matter if Openkneeboard is shown in VR or not. They occur as soon as Openkneeboard App is running.

Back to 1.3.4 and i don't see them. Close Openkneeboard App and they are gone as well.

My Headset is a Reverb G2. Intel i9 13900k, 4090, 64 GB, Windows 11.
I'm running DCS with Motion smoothing enabled via OpenVR -> SteamVR -> WMR for SteamVR -> WMR.
Maybe thats why i even notice the spikes in the otherwise flat curve. Someone without Motion smoothing might miss them.

Thank you.

Sile

example 1 OKR running
![openkneeboard running](https://user-images.githubusercontent.com/123826598/221348329-b804e2d9-c845-4b33-a0e7-79a3cffe0550.jpg)

example 1 OKR closed 
![openkneeboard not running](https://user-images.githubusercontent.com/123826598/221348330-4183d27e-4118-488f-88ea-88d2e9c6d5d5.jpg)

example 2 OKR running
![okb running](https://user-images.githubusercontent.com/123826598/221348358-06cfd73a-982c-4502-a5ed-329688cc75a6.jpg)

example 2 OKR closed
![okb not running](https://user-images.githubusercontent.com/123826598/221348359-c76ec2f9-481e-44dc-8bcb-93a84e6d8c42.jpg)

**Comment by fredemmott** [comment]
What's the scale of these spikes?

From my testing, it appears this is an improvement compared to v1.3 - there's no spikes in v1.3 because the load *all the time* was at the top of what are now spikes.

> exactly every second
> It doesn't matter if Openkneeboard is shown in VR or not

It updates for the clock (even if not visible in VR, it updates for the app); you can turn this off by disabling the footer in advanced settings.

I've checked that while hidden, it doesn't do anything with steamvr or the game - but as it does use the GPU to render, and **it only renders when something's changed** (like the clock's seconds counter), overall GPU usage (and charts that are affected by them) should not be a flat graph - a flat graph would be a bug and mean that it's rendering and eating up GPU time when it doesn't need to. There could be a bug here depending on the size of the spikes. On the extreme end, 5ms would be clearly a bug, .01ms isn't

**Comment by fredemmott** [comment]
> What's the scale of these spikes?

For example, while I can see them and measure them, on my 3090 the entire render pass is between 30000 and 60000 nanoseconds, or 0.03-0.06ms, which is not an issue.

**Comment by matthlsile** [comment]
The scale of the DCS (RCTRL+Pause) frametime graph is 0 - 100 ms. Sorry for the low res. The screenshots didn't turn out as intended.

So i guess while the spikes are quite small in the Main menu (example 1) they reach about 10 ms in flight (example 2 = Caucasus Freeflight).
What i don't understand is why the green and white curve have diametrical peaks.

I think i will try again with footer off recommendation later.

And honestly i didn't feel a lower performance with 1.4. I was just irritated and wanted to let you know of my observation.
But now I'm a bit afraid openkneeboard 1.4 messes with my motion smoothing because of what i see in the performance graphs. Like motion smoothing get's out of steps every second.

**Comment by fredemmott** [comment]
On-GPU time for these passes is < 0.02ms; this could be CPU contention.

![image](https://user-images.githubusercontent.com/360927/221359935-764a4635-9617-41f2-b30e-ebac8127ebc4.png)

**Comment by fredemmott** [comment]
> But now I'm a bit afraid openkneeboard 1.4 messes with my motion smoothing because of what i see in the performance graphs. Like motion smoothing get's out of steps every second.

I'll see if I can get some opinions on this. I'll  also see if I can make it so that clock updates don't lead to repaints when invisible - whether or not that's suitable for v1.4 depends on how big of a change it is.

**Comment by fredemmott** [comment]
on the other side of things, < 0.04ms is taken sending the current in-game time from DCS to OpenKneeboard:

![image](https://user-images.githubusercontent.com/360927/221365047-e3c75357-2e52-4f38-b533-7eb95cca63ad.png)

**Comment by fredemmott** [comment]
> they reach about 10 ms in flight (example 2 = Caucasus Freeflight).

This isn't acceptable, and taking a look a these.

**Comment by matthlsile** [comment]
1.4 beta 3:
Feedback on footer / clock: - spikes every second without footer (disabled), too.

And what i just noticed. 
As soon as DCS has loaded to the Menu the OKB 1.4 in VR freezes. In SteamVR environment and during loading it works. 
- But it doesn't take any pen input once DCS Menu has loadeed..
- With footer enabled the clock freezes - seconds don't tick. (but still spikes every second)
- Can't change Tabs/Pages with my bind. But i can still toggle the OKB visibility.
- Once I quit DCS everything works fine again. Binds, Clock, pen inputs - without restarting OKB.

**Comment by fredemmott** [comment]
Before: 
![image](https://user-images.githubusercontent.com/360927/221377626-65b060ca-8c6c-46aa-ad2c-c1adad0e0623.png)

After:

![image](https://user-images.githubusercontent.com/360927/221377642-af4f87d5-e00a-4d1b-8d3c-31bf35750b6f.png)

Reintroduced the -beta1 'old frames' bug, but will need to figure that out separately

**Comment by fredemmott** [comment]
> Feedback on footer / clock: - spikes every second without footer (disabled), too.

Heh, nice timing :) there's two things that happen every second:
 - OpenKneeboard internally updates the clock which causes a re-render
 - DCS sends OpenKneeboard the in-game time
 
Turns out that this isn't a render performance issue - a change in -beta3 made processing information from DCS *sometimes* be extremely CPU-consuming.

**Comment by fredemmott** [comment]
![image](https://user-images.githubusercontent.com/360927/221377767-9971c9f1-bfac-4015-92ec-84e0e40cd9ef.png)
