### ISSUE TITLE
Add a tab default naming

### ISSUE THREAD

**Issue by 01g8r** [OpenKneeboard/OpenKneeboard#290]
When you click "Add a Tab" it says "DCS Terrain Kneeboard" the tab is Theater, "DCS Mission Briefing" is Briefing and "DCS Mission Kneeboard" is Mission.  It might avoid confusion if they were the same.

I also noticed on Instant Action Mission, AH-64, Caucasus Runway Start the DCS kneeboard has 5 or 6 pages with maps showing the preloaded waypoints.  I don't see those in OpenKneeboard.

**Comment by fredemmott** [comment]
Edited the title to track a single issue per github issue.

As for the extra pages, DCS - and various modules - have pages implemented in Lua that heavily depend on DCS internals. OpenKneeboard attempts to display the kneeboard *image files* that DCS shows, but AFAIK the Lua ones currently directly draw to the DCS kneeboard - they're not exportable.

**Comment by 01g8r** [comment]
Understood.  Thank you.

**Comment by fredemmott** [comment]
I've replaced 'Terrain' with 'Theater'

>  "DCS Mission Briefing" is Briefing and "DCS Mission Kneeboard" is Mission

I'm leaving these as-is: the in-game name needs to be short, but the shorter forms are ambiguous. The difference between 'Mission Briefing' and 'Mission Kneeboard' is important, but I couldn't figure out a good way to fit this into a single word.

Similarly:
- I'm using 'DCS Theater Kneeboard' here instead of just 'Theater' just for consistency with 'DCS Mission Kneeboard'.
- I put 'DCS' in the add-tab name as OpenKneeboard works with other games, but these tabs only work with DCS
