### ISSUE TITLE
Having two wacoms tablets at the same time.

### ISSUE THREAD

**Issue by nittch** [OpenKneeboard/OpenKneeboard#295]
As discussed, creating an issue to have two wacom tablets working at the same time.

Discussion history:
nittch — [...]
anyway I could not find it anywhere, is it supported to have two wacom tablets plugged at the same time? (like intuos pro for drawing, intuos small for cockpit)
Fred — [...]
That can work with opentabletdriver, though there’s a few extra steps there getting pressure sensitivity working with windows ink, which I guess you’d need for the drawing
Hmm, could you file an issue? Got two Wacom’s now, can take a look at making it work with wacoms 
Multiple tablets from multiple vendors will only be possible if at least one is using opentabletdriver because of design limitations of wintab

**Comment by fredemmott** [comment]
Would you need OpenKneeboard to actively suppress the 'drawing' kneeboard, or just to recognize that there are two connected, and for OpenKneeboard to ignore/do nothing with the 'drawing' one?

In other words, would it be fine if - while OpenKneeboard is running - using the 'drawing' kneeboard still moved the cursor/interacted with your drawing app etc?

**Comment by nittch** [comment]
With your huge and reactive support, in fact I don't need this feature anymore, thanks again!

Anyway, if I buy a second Wacom:
-> I think the most important is to recognize there are two connected, maybe expose the orientation/bindings of both
-> but I don't think it's important to actively suppress inputs from the drawing tablet.

**Comment by fredemmott** [comment]
Closing: realistically I'm not going to spend the time to make this work with wintab:
- It works with OpenTabletDriver
- It's a very niche case
- It would only be possible to make it work with wintab if all tablets were from the same vendor. If, for example, you have a nice big wacom tablet for art and a nice cheap huion for flight sim, you still need OpenTabletDriver; this is due to the design of wintab which is over 35 years old now. For a 1989 API it's honestly great, but, it's still 100% compatible and hasn't outgrown its' original limitations.
