### ISSUE TITLE
Crashes if windows fails to provide a path to 'saved games'

### ISSUE THREAD

**Issue by lowki** [OpenKneeboard/OpenKneeboard#402]
Hi.
I've just installed the latest Windows release but it doesn't seem to start at all.
Here's a dump file, hope it helps.
[OpenKneeboardApp.exe.11676.zip](https://github.com/OpenKneeboard/OpenKneeboard/files/12622041/OpenKneeboardApp.exe.11676.zip)

**Comment by fredemmott** [comment]
OpenKneeboard depends on your 'Saved Games' folder, but Windows is reporting there is none.

- Are you using a server or enterprise edition of windows?
- Is there anything 'unusual' (e.g. ntfs junctions) about your saved games folder?
- Are you running it elevated or as another user?

**Comment by lowki** [comment]
> OpenKneeboard depends on your 'Saved Games' folder, but Windows is reporting there is none.
> 
> * Are you using a server or enterprise edition of windows?
> * Is there anything 'unusual' (e.g. ntfs junctions) about your saved games folder?
> * Are you running it elevated or as another user?

My SavedGames folder is on another disk, may I specify it to OpenKneeboard with a config file or a parameter?

**Comment by fredemmott** [comment]
OpenKneeboard does not need it to be in any particular place, and it is configured via Windows; the problem is that Windows is saying your saved games folder doesn't exist, not that it's moved - specifically, `SHGetKnownFolderPath(FOLDERID_SavedGames, ...)` is failing. Your Windows configuration needs fixing, and this kind of issue does cause issues in other games.

If the Saved Games folder is moved - even to another drive - in the special way windows needs to understand this, OpenKneeboard will use the new location.

I'm guessing that start -> run `shell:SavedGames` doesn't work for you either?

I think you're likely to need to:
1. re-create the 'saved games' folder in the default location (`%USERPROFILE%\Saved Games`, most likely `C:\Users\yourusername\Saved Games`)
2. Find it in Explorer
3. right click -> properties
4. Switch to the special 'location' tab (screenshot below)
5. Put in the new location and click 'move'

It will ask if you want to move the content or not, or just change the path; I don't think you'll want to, as your existing saved games are in that path. 

![image](https://github.com/OpenKneeboard/OpenKneeboard/assets/360927/d46569b8-540c-4631-91d4-d1b550a0b48f)

**Comment by fredemmott** [comment]
Next version will show this:

![image](https://github.com/OpenKneeboard/OpenKneeboard/assets/360927/9f1be48d-bafe-4946-a545-1a613bb68ce2)

**Comment by fredemmott** [comment]
If re-creating and moving doesn't fix it, the batch file on https://www.elevenforum.com/t/move-or-restore-default-location-of-saved-games-folder-in-windows-11.8717/ appears to have the registry keys that need to be set

**Comment by lowki** [comment]
Thanks for your inputs, my "Saved Games" folder wasn't set  in environment variables.
It will really helps to have this error message 👍
