### ISSUE TITLE
Openkneeboard causing DCS to CTD?

### ISSUE THREAD

**Issue by SpectreBit** [OpenKneeboard/OpenKneeboard#480]
As soon as I use my "Next Tab" keybind, my DCS will crash. Happens every single time I do it. It is not crashing Openkneeboard. Any ideas? Was working consistently before.

I have attached the DCS.log and created an Openkneeboard dump, download from this link: https://filetransfer.io/data-package/i4PGY8Rs#link

From the DCS.log:
(edCore):
ed::current_exception_stack_trace + 0x279
(ucrtbase):
raise + 0x1E5
(ucrtbase):
abort + 0x31
(ucrtbase):
terminate + 0x29
**(OpenKneeboard-OpenXR):
OpenKneeboard_xrNegotiateLoaderApiLayerInterface + 0xD77C1**
[...]

**Comment by fredemmott** [comment]
Thanks for the dumps - can you also attach the OpenKneeboard logs after a crash? Ideally start Openkneeboard before DCS so the logs contain the DCS startup.

![image](https://github.com/OpenKneeboard/OpenKneeboard/assets/360927/71512317-c84f-4769-94c2-085a4f937a9e)

**Comment by SpectreBit** [comment]
[OpenKneeboard-v1.7.0.1655-2024-01-18-15-04.zip](https://github.com/OpenKneeboard/OpenKneeboard/files/13981605/OpenKneeboard-v1.7.0.1655-2024-01-18-15-04.zip)

**Comment by SpectreBit** [comment]
Can confirm that it does not crash if openkneeboard isn't running when I press that keybind.

**Comment by fredemmott** [comment]
I see you've tried a few different versions; the error that's happening under v1.7.4-alpha4 is *probably* fixed by this build: https://nightly.link/OpenKneeboard/OpenKneeboard/actions/runs/7564477142/OpenKneeboard-GHA1659.msi.zip - does that build work for you?

There's insufficient information in the logs to see if that's the same issue causing crashing under v1.6.4

The issue that's fixed by that build is that it doesn't correctly handle situations when the image + the toolbars etc are together taller or wider than 2048px

**Comment by SpectreBit** [comment]
I will try it out. I was not aware I was using different versions, I had performed the most recent update (a couple days ago I think?)

**Comment by SpectreBit** [comment]
The version you sent works without issues. Thank you.
