### ISSUE TITLE
Feature Request:  Support wildcard operators in the full path of a window capture tab "Executable" value set in Tabs.json

### ISSUE THREAD

**Issue by dustinsterk** [OpenKneeboard/OpenKneeboard#497]
Fantastic work on the multiple kneeboards addition, I can finally use multiple overlays in OpenXR while sim racing!  One minor feature I would love to see is the ability to use wildcards in a new tab "Executable" path (that is set in Tabs.json).  Certain software has the version number in the .exe full path, and when such software updates, I have to edit the Tabs.json file for every tab that was added using that old path version.  A minor nit, but figured it could be an enhancement others would also benefit from.

Ex) Once the tabs have been set in the GUI, the Tabs.json could be manually edited from:  "Executable": "C:\\Users\\JonSmith\\AppData\\Local\\mysoftware\\app-1.1\\Apps.exe" to "C:\\Users\\JonSmith\\AppData\\Local\\mysoftware\\app-*\\Apps.exe" and the software could perform a search operation to find the .exe full path name in place of the asterisk symbol above.

Thanks again for all the great work!

**Comment by dustinsterk** [comment]
As a workaround, I have just written a powershell script for windows machines that will fix the Tabs.json file (assumes using the default openknee profile).  This code is specifically for a popular sim racing overlay application RaceLapApps which uses the version number in the path to the .exe, thus breaking OpenKnee Overlay Tabs config when the app updates.  I still hope this feature request is considered, but this will work for now and for anyone else looking for other workarounds.

**Code (copy/paste and save as .ps1 file, right click and 'run with powershell' after a new version install):**
```
$OKBConfig = "$Env:USERPROFILE\Saved Games\OpenKneeboard\profiles\default\Tabs.json"
$RLAppPath=Resolve-Path "$Env:USERPROFILE\AppData\Local\racelabapps\app-*" | Select -ExpandProperty Path
$RLAppVersion= Split-Path $RLAppPath -Leaf

Write-Host "Updating $OKBConfig with $RLAppVersion"

$tmp = (Get-Content $OKBConfig) -replace '(app-[^\\]+)', $RLAppVersion; [System.IO.File]::WriteAllLines($OKBConfig, $tmp)

Write-Host -NoNewLine 'Complete.  Press any key to continue...';
$null = $Host.UI.RawUI.ReadKey('NoEcho,IncludeKeyDown');
```

**Comment by fredemmott** [comment]
Implemented using what Microsoft vaguely describe as "a string that contains the file type for which to search. For example, to test whether pszFile is a .doc file, pszSpec should be set to "*.doc".". In other places, Microsoft define it as 'MS-DOS path patterns', but I'm not seeing a full definition of that. It at least works for `*` anywhere in the path, not just for file types, but there's not a full description of the limitations.

It still requires editing the configuration file *once* to add the wildcards as:
- it breaks showing the game icon
- game-specific functionality can be easily broken by this; e.g. changing an existing entry to point to DCS World should also involve changing the type to 'DCS', otherwise the game-specific hooks will not be installed.

**Comment by fredemmott** [comment]
I did this for game paths, not capture

**Comment by fredemmott** [comment]
Example config:

```JSON
    "Settings": {
      "Spec": {
        "ExecutableLastSeenPath": "C:\\Users\\fred\\code\\imgui\\examples\\example_win32_directx11\\Debug\\example_win32_directx11.exe",
        "ExecutablePathPattern": "C:\\Users\\fred\\code\\imgui\\examples\\example_win32_directx11\\*\\example_win32_directx11.exe",
        "Title": "Dear ImGui DirectX11 Example",
        "WindowClass": "ImGui Example"
      }
    },
```

LastSeenPath is used for performance

**Comment by dustinsterk** [comment]
Awesome, thank you!!!
