### ISSUE TITLE
Crash when editing Radio Log after switching profiles

### ISSUE THREAD

**Issue by GussyH** [OpenKneeboard/OpenKneeboard#557]
- Select Profile
- In Settings -> Tabs click cog to edit Radio Log tab
- Make changes and close
- Change profile
- Click cog to change settings Radio Tab in this profile
- OpenKneeboard crashes

**Comment by fredemmott** [comment]
So, the tabs list is being updated with new elements.

Tried, doesn't fix it:

- ❌ reimplementing `Equals()` and `HashCode()` in case of ListView equality thing considering the new tabs the same
- ❌ explicitly manipulating the vector of items instead of using the XAML properties system to set the new tabs
- ❌ adding a new radio log tab in the other profile, instead of both having the same ID
- ❌ adding a 1 second delay in between the profile change and updating the UI, to see if this is a call ordering issue

**Comment by fredemmott** [comment]
- ❌ replacing all `OneTime` XAML bindings with `OneWay` so that they definitely update

**Comment by fredemmott** [comment]
-❌ nulling out the TabSettingsDialogContent before showing it

**Comment by fredemmott** [comment]
This seems to be either a XAML binding issue, or a WinUI3 ContentDialog bug:

```C++
  auto uiData = CreateTabUIData(tab);
  TabSettingsDialogContent().Content(uiData);
  TabSettingsDialogContent().ContentTemplateSelector(
    TabSettingsTemplateSelector());
  co_await TabSettingsDialog().ShowAsync();
```

The tab is valid, and the uiData is a `DCSRadioLogTabUIData` containing a valid reference to the tab - but the XAML is reading from a stale version of it.

**Comment by fredemmott** [comment]
I *think* this is a caching bug in WinUI3 `ContentPresenter`:
