### ISSUE TITLE
Crash with invalid URL?

### ISSUE THREAD

**Issue by Todd1215** [OpenKneeboard/OpenKneeboard#634]
I've updated OKB to the latest version and after the update it won't open unless I remove the current Saved Games folder for OKB. Attached is the zip of the offending OKB folder saved games folder and the crash dump
[OpenKneeboardApp.exe.1288.dmp.zip](https://github.com/user-attachments/files/16489584/OpenKneeboardApp.exe.1288.dmp.zip)
[OpenKneeboardBAD.zip](https://github.com/user-attachments/files/16489585/OpenKneeboardBAD.zip)

**Comment by fredemmott** [comment]
Thanks; unfortuantely there's not enough information in the dump to see what's going on, other than it's something involving a web dashboard.

Can you either (or better, both):
- [share a trace](https://openkneeboard.com/troubleshooting/logs-and-traces.html#standard-traces)
- [share a full dump instead of a minidump](https://openkneeboard.com/troubleshooting/crashes-and-freezes.html#getting-a-dump-file-for-a-crash)

**Comment by Todd1215** [comment]
Yeah I figured it out. Apparenty the web dashboard was saving a URL that didn't exist any longer. Removing the URL and replace it with a good one worked.

**Comment by fredemmott** [comment]
Glad this is fixed for you :) re-opening so I don't forget to see if I can reproduce/debug this that extra info :)

**Comment by fredemmott** [comment]
Unable to reproduce a problem here unfortunately, even with the URLs from your config file
