### ISSUE TITLE
fix header/footer bleeding into cropped texture subregion

### ISSUE THREAD

**Issue by otherguy485** [OpenKneeboard/OpenKneeboard#658]
I have no way of taking a picture of this that I know of because I only see it in VR.

Some overlays have a thin black line at the top of where the boundary of where the overlay would be, and it's only at the top.
It might be on all of them, but I only notice it on a couple that are in the windshield where the background is light colored behind the overlay.

Wonder if anyone has seen this or how if there is a way to remove it?

---

Edit by @fredemmott to put a summary at the top:

As of 2024-10-31:

- workaround: turn off headers and footers in advanced settings under 'in-game interface', not just the per-view settings
- fix status: fixed for 1.9.11 with D3D11 and Vulkan, not yet fixed for D3D12

**Comment by fredemmott** [comment]
Which overlays?

**Comment by otherguy485** [comment]
The ones I notice on (because I have them above my wheel on my windshield) is the spotter ones, doesn't matter what program, JRT, Racelab, iOverlay, all the spotter/radar overlays have that black line across the top.  I really notice it because the overlay is blank/not visible when not in use so that line is there.

Again, the other might have them too, but I wouldn't notice them since they are on a dark background, either the dash or roof of the car.  I have never moved one to see.

**Comment by fredemmott** [comment]
As you said it's only in VR:
- have you tried [the test viewer](https://openkneeboard.com/how-to/OpenKneeboard-Viewer.html) ?
- what headset?
- what runtime?
- what VR API?

**Comment by otherguy485** [comment]
• I have not, but I did open it but only see one overlay not sure how to toggle through them.
• Reverb G2
• OpenXR
• WMR, just running OpenXR through iRacing, so no SteamVR or anything.

I did go in VR and noticed something, the black line appears on the overlay (any of them) that I look directly at, as in overlay is centered in the headset view, and since the radar is in the middle of the screen basically it always shows up.

I tested this by looking at the track map and the line shows up, if I look at another overlay with more my eyes and not centering the headset on it the lines stays with the track map, but if I move my head and look directly at the overlay the line moves to that overlay.

Since the radar was center screen the line was always showing up.

![IMG_1671](https://github.com/user-attachments/assets/c83a79fb-3aa7-4d2e-a5c7-19220f43faa4)

**Comment by fredemmott** [comment]
'v' to switch it between mirroring VR and non-VR views (only the first view is available outside VR) then 1-9 to show a specific view.

Are these window captures or web dashboards?

**Comment by otherguy485** [comment]
Window captures

**Comment by fredemmott** [comment]
Can you reproduce this with any simhub overlays?

- I'm not OK with Racelab's terms of service
- Spotter is no longer free in iOverlay
- old versions of iOverlay now say an update is *required* and immediately exit if I try to use them

**Comment by fredemmott** [comment]
JRT is also not free so not going to look into it, however from looking at their docs, you might want to try using their overlay feature with spotter.html and a web dashboard tab instead of window capture.

**Comment by otherguy485** [comment]
It should happen on any of iOverlay overlays, it’s not specific to spotter that was just the one that happened to be in light background.

**Comment by fredemmott** [comment]
Sorry, I'm not able to reproduce this with ioverlay standings on:
- Meta Link
- Virtual Desktop
- SteamVR (Pimax, quest, + a steamvr-native headeest)
- Meta XR Simulator (screenshot below)

![image](https://github.com/user-attachments/assets/92ba67f1-3623-4d7f-9d63-c5b2f9dcd037)

**Comment by ithergames** [comment]
I'm using a Bigscreen Beyond in iRacing with OpenXR enabled. I too am getting this thin black line randomly.

For me, it's happening with Racelab Radar in both web capture mode and web dashboard mode.
I can also get the line to start appear on the Mini Map in both modes if I tilt my head a certain angle.

**Comment by ithergames** [comment]
I've identified that this is happening when I look at it. I have gaze zoom turned off on this profile but if I look towards the overlay the black line appears. The same thing happens on all of them. The blind spot is always on because it's "window" is pretty large in my view port in order to put the radar exactly where I want it.

I cannot find an option to disable whatever this line is when looking at the overlay. I tried recording it through my eyeview but it's impossible.

**Comment by ithergames** [comment]
> • I have not, but I did open it but only see one overlay not sure how to toggle through them. • Reverb G2 • OpenXR • WMR, just running OpenXR through iRacing, so no SteamVR or anything.
> 
> I did go in VR and noticed something, the black line appears on the overlay (any of them) that I look directly at, as in overlay is centered in the headset view, and since the radar is in the middle of the screen basically it always shows up.
> 
> I tested this by looking at the track map and the line shows up, if I look at another overlay with more my eyes and not centering the headset on it the lines stays with the track map, but if I move my head and look directly at the overlay the line moves to that overlay.
> 
> Since the radar was center screen the line was always showing up.
> 
> ![IMG_1671](https://private-user-images.githubusercontent.com/159829812/366586524-c83a79fb-3aa7-4d2e-a5c7-19220f43faa4.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgxNTAyODEsIm5iZiI6MTcyODE0OTk4MSwicGF0aCI6Ii8xNTk4Mjk4MTIvMzY2NTg2NTI0LWM4M2E3OWZiLTNhYTctNGQyZS1hNWM3LTE5MjIwZjQzZmFhNC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwNVQxNzM5NDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03ZTBiMTEyNGVjNWIxY2RjYjg5NDA0YzQ1NmMyYzllZjIyYmRlNTdmM2NkZDdmMmRhZWUwNzAyZGJmMjRiZmI2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.aWVtkQxMb1HcAXg3lAu34O5-Y2C-3hP8Dz_Zc982ol4)

I'm having your exact problem. It's a gaze issue. If I look away from it the line disappears, look back at it, and it's back. My radar is right in middle so it's always turned on.

**Comment by fredemmott** [comment]
Ah, that makes sense, including why I dont' see it - it's not just for transparent, it's just pretty subtle in other situations - this line is the marker for which view is affected by bindings if you don't have a tablet/headers/footers, which added to fix #517.

**Comment by fredemmott** [comment]
To reproduce the problem:
- close OpenTabletDriver or uninstall vendor drivers, and restart OpenKneeboard
- turn headers and footers *on* in advanced settings
- turn headers and footers *off* in VR per-view settings

This leads to:
- the header and footer - including this line - are rendering, as it's needed for non-VR views
- this includes the active view marker
- either downscaling, incorrect cropping, or both are leading to it being (partially) visible in the VR view

Left: non-VR with heavy black line at the top (as expected for this configuration)
Right: VR mirror with more subtle line - it looks smaller as it's *only* the extra line, rather than the extra line + the line that's always part of the header border. There might also be an incorrect cropping issue at the bottom


![image](https://github.com/user-attachments/assets/2d8573ce-6a5d-4509-958b-b5789c9a2c29)

Workaround: turn off headers and footers in advanced settings under 'in-game interface', not just per-view settings

![image](https://github.com/user-attachments/assets/31a49748-e87c-4182-8617-bc9b8b9c7492)

**Comment by ithergames** [comment]
TY!
This fixed it!

**Comment by fredemmott** [comment]
To investigate/fix:
- [ ] line at bottom may simply be a cropping bug - check :)
- [ ] split the indicator to a separate UI layer
- [ ] figure out better logic for this. Perhaps it should just always be cropped out if the header/footer is meant to be cropped out

The current 'active view' indicators are:
- if using a tablet, the header contains buttons
- if you're not using a tablet, the line is added

This is because the buttons aren't clickable unless you have a tablet and they were confusing people.

Now that headers/footers can be turned off, the status quo doesn't make sense:
- if you have headers/footers turned off globally you always have no indicator
- if you have them turned on globally but turned off in the view:
  - if you have a tablet, the indicator is hidden, as the buttons are cropped out
  - if you don't have a tablet, the tablet is visible
  
Two problems here:
- turning off headers/footers globally should be equivalent to turning them off in every view
- with header/footer turned off in view, having a visual indicator of active view only if you *don't* have a tablet doesn't make sense

**Comment by otherguy485** [comment]
Workaround: turn off headers and footers in advanced settings under
'in-game interface', not just per-view settings

This workaround is all I need to do correct?

**Comment by fredemmott** [comment]
> This workaround is all I need to do correct?

Yep

**Comment by fredemmott** [comment]
Test image:

<img width="332" alt="cropping" src="https://github.com/user-attachments/assets/7b313d1e-7ba4-47f2-83ca-589bf0d386b9">

0.5px offset fixes the issue when scaling, but artifacts when drawing unscaled

<img width="146" alt="image" src="https://github.com/user-attachments/assets/09abea09-9d44-495d-a76a-0e3e8fdd2ee3">

**Comment by fredemmott** [comment]
The best way to do this is probably to move to `CopySubresourceRegion()`/`vkCmdCopyImage()` etc instead of draw calls. This will require removing the upscaling option, which currently is needed for decent quality on Varjo headsets.

I'll probably remove this option, reducing the quality on Varjo headsets. Reached out to varjo with:

> > OpenXR: Upscale Images
> > 
> > Automatic (Varjo only)
> 
> If I give the Varjo OpenXR runtime quad layers at a low resolution, the quality is *significantly* worse than any other runtime. When this option is on, I just do linear up to an arbitrary (up to 2048px in either dimension) and the quality improvement is huge. It looks like Varjo just does point sampling?
> 
> I want to remove this option entirely because:
> - runtime-specific behavior hugely increases testing complexity as a developer
> - it means that I need to do actual draw calls in my API layer, rather than `CopySubResourceRegion()` or `vkCmdCopyImage`  etc. This hugely increases complexity - and bluntly I don't want to maintain this complexity just for Varjo, especially as I need to duplicate it for D3D11, D3D12, and Vulkan
> 
> # Requests for Varjo
> 
> 1. Ideally, could you match other runtimes, and introduce at-least linear scaling for composition layers?
> 2. Otherwise, is there an API to enable this?
>   - The closest thing I see is `XR_FB_composition_layer_settings` - while currently no PC runtimes are marked as supporting this, adding `XR_COMPOSITION_LAYER_SETTINGS_NORMAL_SUPER_SAMPLING_BIT_FB` would be a reasonable amount of 'just needed varjo' code to maintain
>  -  `XR_META_recommended_layer_resolution` might theoretically be better, but also no PC runtimes are marked as supporting it - and if Varjo added support, this wouuld need keeping the draw calls, in practice still just for Varjo
> 3. Is there a setting somewhere (registry?) I could point users at to get better quality?

**Comment by fredemmott** [comment]
I think I have this fixed *for Vulkan only* with a further-customized pixelshader. I did this with Vulkan as OpenKneeboard's Vulkan support is from scratch giving me full control, while D3D11 and D3D12 are based on some Microsoft libraries that are much more restricted.

If I keep this approach, I'll probably move D3D11 and D3D12 from Microsoft's library to a from-scratch implementation

The cropping test image shows that al lthe pixels are being preserved; it looks like there's still a dark line at top/bottom to me, but zooming in on the screenshot shows this is an optical illusion due to the striped boundaries:

<img width="1408" alt="image" src="https://github.com/user-attachments/assets/1d3e16a1-e116-43ae-b2ad-c8f2f584ec63">

A solid color image makes it clearer that the cropping is fixed, as it's immune to the border optical illusion:

<img width="1408" alt="image" src="https://github.com/user-attachments/assets/6e667ea2-c3d3-49fc-b512-d5aa77fa630f">

**Comment by fredemmott** [comment]
D3D11 will be much more painful due to lack of support for shader model 5.1 including non uniform resource indexing. May use the D3D12 implementation on the D3D11 surfaces. This may have a slight performance impact on the varjo openxr runtime but not in others, as the lack of SHARED/SHARED_NTHANDLE support on swap chain textures introducing the need for intermediate copies. The standards don't require this, it's just convenient/useful/efficient that other runtimes provide it

**Comment by rocketeer998** [comment]
otherguy485, you suggestion to turn off header toolbar in the In-Game UI under Advanced setting works. I had previously turned it off in both kneeboards 1 and 2 view. And still had a line in VR for various aircrafts. But now I read your suggestion and turned it off in the Advanced Settings UI. Now the line is gone! Thank you!

**Comment by fredemmott** [comment]
What version are you running exactly, and what game?

- D3D11 + Vulkan: you need the latest *testing* version (v1.9.12)
- D3D12: fixed for *next* release

**Comment by otherguy485** [comment]
This was my version which was updated a couple of days ago, but now I see
there is another update.
Game: iRacing

[image: image.png]

**Comment by fredemmott** [comment]
Your image attachments don't work via email; either use text, or reply on the github website if you need to use an image

**Comment by otherguy485** [comment]
V1.8.14+gha.2483 is the version I am on, updated from a couple of days ago,
so will update to the latest version.
