### ISSUE TITLE
v1.9: can't write in endless pages

### ISSUE THREAD

**Issue by flanker0ne** [OpenKneeboard/OpenKneeboard#710]
I can write with mouse or pen in all others kinds of documents but the endless pages

**Comment by fredemmott** [comment]
- please attach logs: https://openkneeboard.com/troubleshooting/logs-and-traces/#saving-debug-logs
- please attach the file you're using as a template for the endless pages
- do you have this problem when drawing in the OpenKneeboard app window?
- do you have this problem when drawing with the tablet when the game window is active?
- what happens when you try to write?

**Comment by fredemmott** [comment]
I can reproduce this with this test image as a template
![01-narrow](https://github.com/user-attachments/assets/9ded5bf1-e0f9-4aac-9dd9-2a8f346ad1d6)
